source 'https://github.com/CocoaPods/Specs.git'
#source 'https://git.yoomoney.ru/scm/sdk/cocoa-pod-specs.git'

target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'umbrella', :path => '../shared/umbrella'
  pod 'KMPNativeCoroutinesAsync', '1.0.0-ALPHA-18'
  pod 'KMMViewModelSwiftUI', '1.0.0-ALPHA-14'
  pod 'Firebase/Core'
  pod 'FirebaseCrashlytics'
  pod 'FirebaseMessaging'
  pod 'lottie-ios'
#  pod 'YooKassaPayments', :git => 'https://git.yoomoney.ru/scm/sdk/yookassa-payments-swift.git'
  pod 'YandexMobileAds', '6.4.0'
  pod 'YandexMobileAdsInstream', '0.24.0'

end

 post_install do |installer|
   installer.aggregate_targets.each do |target|
     target.xcconfigs.each do |variant, xcconfig|
       xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
       IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
     end
   end
   installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
       if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
         xcconfig_path = config.base_configuration_reference.real_path
         IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
       end
     end
   end
   installer.pods_project.targets.each do |target|
     if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
       target.build_configurations.each do |config|
           config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
       end
     end
   end
 end
